#!/usr/bin/env node
'use strict';
// Hermetic contract for the brand-agent catalog + advisors surfaces.
// Grounds product specs in tree state after the fleet brand-leaf work.

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const brand = JSON.parse(fs.readFileSync(path.join(REPO, 'config', 'brand-agents.json'), 'utf8'));
const map = JSON.parse(fs.readFileSync(path.join(REPO, 'config', 'model-map.json'), 'utf8'));
const a2c = map.agent_to_capability || {};
const routes = map.model_routes || {};
const cthru = fs.readFileSync(path.join(REPO, 'tools', 'c-thru'), 'utf8');
const MARKER = '<!-- GENERATED by tools/gen-brand-agents.js; edits will be overwritten. -->';

let passed = 0;
let failed = 0;
function assert(cond, msg) {
  if (cond) { console.log(`  PASS  ${msg}`); passed++; }
  else { console.error(`  FAIL  ${msg}`); failed++; }
}

function covers(model) {
  if (Object.prototype.hasOwnProperty.call(routes, model)) return true;
  const latest = map.latest_models?.[model];
  if (latest && latest !== model) return covers(latest);
  for (const k of Object.keys(routes)) {
    if (!k.startsWith('re:')) continue;
    try { if (new RegExp(k.slice(3)).test(model)) return true; } catch (_) { /* ignore */ }
  }
  return false;
}

console.log('brand-fleet-contract\n');

// ── 1. Catalog integrity ────────────────────────────────────────────────────
console.log('1. Catalog pins and routes');
{
  let n = 0;
  for (const a of brand.agents || []) {
    n++;
    assert(typeof a.pin === 'string' && a.pin.startsWith('model:'),
      `${a.id}: pin is model:<…>`);
    assert(a2c[a.id] === a.pin, `${a.id}: a2c matches catalog pin`);
    const bare = a.pin.slice('model:'.length);
    assert(covers(bare), `${a.id}: pin target '${bare}' has model_routes coverage`);
    for (const al of a.aliases || []) {
      const id = typeof al === 'string' ? al : al.id;
      const pin = typeof al === 'string' ? a.pin : (al.pin || a.pin);
      assert(a2c[id] === pin, `alias ${id}: a2c matches pin`);
      assert(covers(pin.slice('model:'.length)), `alias ${id}: pin target routed`);
      const f = path.join(REPO, 'agents', `${id}.md`);
      assert(fs.existsSync(f), `alias file agents/${id}.md exists`);
    }
    const f = path.join(REPO, 'agents', `${a.id}.md`);
    assert(fs.existsSync(f), `primary file agents/${a.id}.md exists`);
  }
  assert(n >= 20, `catalog has a full primary set (got ${n})`);
}

// ── 2. Selection-friendly descriptions ──────────────────────────────────────
console.log('\n2. Description templates (selection surface)');
{
  for (const a of brand.agents || []) {
    const text = fs.readFileSync(path.join(REPO, 'agents', `${a.id}.md`), 'utf8');
    assert(text.includes(MARKER), `${a.id}: generated ownership marker present`);
    const m = text.match(/^description:\s*(.+)$/m);
    assert(m, `${a.id}: has description line`);
    const desc = m[1];
    assert(/MUST BE USED when the user names/.test(desc),
      `${a.id}: primary lead is name-gated (not "brand routing")`);
    assert(!/brand routing/i.test(desc), `${a.id}: no "brand routing" jargon`);
    assert(/use coder instead/i.test(desc), `${a.id}: coder wall present`);
    assert(/use advisors instead/i.test(desc), `${a.id}: advisors panel wall present`);
    assert(new RegExp(`what would ${a.id} say`).test(desc) || new RegExp(`${a.id}'s take`).test(desc),
      `${a.id}: name-bound paraphrase present`);
  }
  // alias sample: no bare primary name as a separate family invite
  const terraAlias = fs.readFileSync(path.join(REPO, 'agents', 'gpt-5-6-terra.md'), 'utf8');
  const ad = terraAlias.match(/^description:\s*(.+)$/m)[1];
  assert(/exact agent id "gpt-5-6-terra"/.test(ad), 'alias uses exact-id mandate');
  assert(!/\bask terra\b/i.test(ad), 'alias does not invite bare "ask terra"');
}

// ── 3. Codex + advisors product pins ────────────────────────────────────────
console.log('\n3. Codex brand leaves + advisors host');
{
  for (const [id, pin] of [
    ['sol', 'model:sol'],
    ['terra', 'model:terra'],
    ['luna', 'model:luna'],
    ['codex', 'model:codex'],
  ]) {
    assert(a2c[id] === pin, `${id} → ${pin}`);
    assert(covers(pin.slice(6)), `${id} pin target routed`);
  }
  assert(a2c.advisors === 'planner-hard', 'advisors host → planner-hard');
  assert(fs.existsSync(path.join(REPO, 'agents', 'advisors.md')), 'agents/advisors.md');
  assert(fs.existsSync(path.join(REPO, 'skills', 'advisors', 'SKILL.md')), 'skills/advisors');
  assert(fs.existsSync(path.join(REPO, 'commands', 'advisors.md')), 'commands/advisors.md');
  assert(!fs.existsSync(path.join(REPO, 'skills', 'c-thru-advisors')), 'no legacy skill dir');
  assert(!fs.existsSync(path.join(REPO, 'commands', 'c-thru-advisors.md')), 'no legacy command');
}

// ── 4. Parent system-prompt: no builtin/brand contradiction ─────────────────
console.log('\n4. Fleet system-prompt wording');
{
  // Accept compact or long wording (prompt may be edited for token budget).
  assert(/Named[- ]brand|brand leaves|Named brand/i.test(cthru),
    'c-thru mentions named brand / brand leaves');
  assert(/opus\/sonnet\/haiku\/fable/.test(cthru) && /fleet brand leaves/i.test(cthru),
    'prompt clarifies opus/sonnet/haiku/fable are fleet brand leaves');
  // Forbidden: list sonnet/opus/haiku as banned builtins (collides with brand leaves).
  assert(!/Never substitute generic built-in agent types such as sonnet, opus, haiku/.test(cthru),
    'removed contradictory "never substitute … sonnet, opus, haiku" ban');
  assert(/OpenAI API/i.test(cthru) || /OPENAI_API_KEY/.test(cthru),
    'Codex family auth note present (OpenAI API, not subscription CLI)');
  assert(/Multi-model panel\s*→\s*advisors|advisors skill\/agent/i.test(cthru),
    'multi-model panel routes to advisors');
}

// ── 4b. Reserved control docs are not fleet agents ─────────────────────────
console.log('\n4b. Reserved agents/*.md control docs');
{
  const reserved = ['AGENTS.md', 'CLAUDE.md'];
  for (const name of reserved) {
    const p = path.join(REPO, 'agents', name);
    if (!fs.existsSync(p)) {
      assert(true, `${name}: absent (ok)`);
      continue;
    }
    assert(a2c[name.replace(/\.md$/, '')] === undefined,
      `${name}: must not have agent_to_capability entry`);
    assert(/reservedAgentFiles|AGENTS\.md\|CLAUDE\.md/.test(cthru),
      'c-thru inject skips reserved control docs');
  }
}

// ── 4c. Named-brand list is catalog-derived (no drift) ─────────────────────
console.log('\n4c. Named-brand list matches catalog primary ids');
{
  const catalogIds = (brand.agents || []).map(a => a.id).join(', ');
  // Runtime path generates the list from the catalog; the fallback must match
  // so a missing catalog still names every primary leaf (no silent drift).
  const m = cthru.match(/\|\| brand_list="([^"]*)"/);
  assert(m, 'c-thru has a brand_list fallback');
  if (m) {
    assert(m[1] === catalogIds,
      `fallback brand_list matches catalog primary ids (${catalogIds})`);
  }
}

// ── 5. Lean marketplace still excludes advisors skill ───────────────────────
console.log('\n5. Shape C lean (advisors not in plugin skills)');
{
  const lean = path.join(REPO, 'plugins', 'c-thru', 'skills', 'advisors', 'SKILL.md');
  assert(!fs.existsSync(lean), 'plugins/c-thru/skills/advisors must not ship');
}

console.log(`\n${passed + failed} tests: ${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
