#!/usr/bin/env node
'use strict';
// Ownership and stale-artifact tests for tools/gen-brand-agents.js.
// Runs the real generator from an isolated scratch repository.

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const { assert, assertEq, summary } = require('./helpers');

const REPO = path.join(__dirname, '..');
const SCRIPT_SOURCE = path.join(REPO, 'tools', 'gen-brand-agents.js');
const GENERATED_MARKER = '<!-- GENERATED by tools/gen-brand-agents.js; edits will be overwritten. -->';
const OWNERSHIP_KEY = '_generated_brand_agents';

console.log('gen-brand-agents ownership tests\n');

function writeJson(dest, value) {
  fs.writeFileSync(dest, JSON.stringify(value, null, 2) + '\n');
}

function makeFixture(catalogAgents) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'c-thru-brand-agents-'));
  fs.mkdirSync(path.join(root, 'tools'), { recursive: true });
  fs.mkdirSync(path.join(root, 'config'), { recursive: true });
  fs.mkdirSync(path.join(root, 'agents'), { recursive: true });
  fs.mkdirSync(path.join(root, 'plugins', 'c-thru', 'config'), { recursive: true });
  fs.copyFileSync(SCRIPT_SOURCE, path.join(root, 'tools', 'gen-brand-agents.js'));
  writeJson(path.join(root, 'config', 'brand-agents.json'), { agents: catalogAgents });

  const map = {
    model_routes: { 'model-alpha': 'stub' },
    agent_to_capability: { planner: 'planner-hard' },
  };
  writeJson(path.join(root, 'config', 'model-map.json'), map);
  writeJson(path.join(root, 'plugins', 'c-thru', 'config', 'model-map.json'), map);
  fs.writeFileSync(path.join(root, 'agents', 'planner.md'), '# Functional planner role\n');
  return root;
}

function runWithEnv(root, extraEnv, ...args) {
  return spawnSync(process.execPath, [path.join(root, 'tools', 'gen-brand-agents.js'), ...args], {
    encoding: 'utf8',
    env: { ...process.env, ...extraEnv },
  });
}

function run(root, ...args) {
  return runWithEnv(root, {}, ...args);
}

function readMap(root, plugin = false) {
  const dest = plugin
    ? path.join(root, 'plugins', 'c-thru', 'config', 'model-map.json')
    : path.join(root, 'config', 'model-map.json');
  return JSON.parse(fs.readFileSync(dest, 'utf8'));
}

function transactionTemps(root) {
  const found = [];
  function walk(dir) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const dest = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(dest);
      if (/\.gen-brand-agents\.\d+\.\d+\.(?:stage|backup)$/.test(entry.name)) found.push(dest);
    }
  }
  walk(root);
  return found;
}

console.log('1. refuses to overwrite a non-generated role file');
{
  const root = makeFixture([{ id: 'planner', pin: 'model:model-alpha', label: 'Planner Brand' }]);
  try {
    const rolePath = path.join(root, 'agents', 'planner.md');
    const before = fs.readFileSync(rolePath, 'utf8');
    const result = run(root);
    assertEq(result.status, 1, 'role collision exits nonzero');
    assert(
      result.stderr.includes('planner: collides with non-generated agent file agents/planner.md'),
      'collision error identifies the protected role file',
    );
    assertEq(fs.readFileSync(rolePath, 'utf8'), before, 'functional role file is unchanged');
    assertEq(readMap(root).agent_to_capability.planner, 'planner-hard', 'functional role mapping is unchanged');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

console.log('\n2. rejects duplicate primary ids and primary/alias collisions');
for (const [label, agents] of [
  [
    'duplicate primaries',
    [
      { id: 'acme', pin: 'model:model-alpha' },
      { id: 'acme', pin: 'model:model-alpha' },
    ],
  ],
  [
    'primary collides with an earlier alias',
    [
      { id: 'acme', pin: 'model:model-alpha', aliases: ['shared'] },
      { id: 'shared', pin: 'model:model-alpha' },
    ],
  ],
]) {
  const root = makeFixture(agents);
  try {
    const result = run(root);
    assertEq(result.status, 1, `${label}: exits nonzero`);
    assert(result.stderr.includes('duplicate brand agent id'), `${label}: identifies duplicate id`);
    assert(!fs.existsSync(path.join(root, 'agents', 'acme.md')), `${label}: writes no brand agent files`);
    assert(!Object.hasOwn(readMap(root).agent_to_capability, 'acme'), `${label}: writes no brand mapping`);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

console.log('\n3. check requires persisted ownership after generation');
{
  const root = makeFixture([{ id: 'acme', pin: 'model:model-alpha', label: 'Acme' }]);
  try {
    let result = run(root);
    assertEq(result.status, 0, `initial generation succeeds: ${result.stderr}`);
    for (const plugin of [false, true]) {
      const map = readMap(root, plugin);
      delete map[OWNERSHIP_KEY];
      const mapPath = plugin
        ? path.join(root, 'plugins', 'c-thru', 'config', 'model-map.json')
        : path.join(root, 'config', 'model-map.json');
      writeJson(mapPath, map);
    }

    result = run(root, '--check');
    assertEq(result.status, 1, 'check rejects missing generated ownership metadata');
    assert(result.stderr.includes(`config/model-map.json ${OWNERSHIP_KEY}`), 'check reports missing main ownership metadata');
    assert(result.stderr.includes(`plugins/c-thru/config/model-map.json ${OWNERSHIP_KEY}`), 'check reports missing plugin ownership metadata');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

console.log('\n4. an existing generator lock prevents interleaved writes');
{
  const root = makeFixture([{ id: 'acme', pin: 'model:model-alpha', label: 'Acme' }]);
  try {
    fs.writeFileSync(path.join(root, '.gen-brand-agents.lock'), 'other-run\n');
    const result = run(root);
    assertEq(result.status, 1, 'locked generator exits nonzero');
    assert(result.stderr.includes('another generator run holds'), 'locked generator reports contention');
    assert(!fs.existsSync(path.join(root, 'agents', 'acme.md')), 'locked generator writes no agent files');
    assert(!Object.hasOwn(readMap(root).agent_to_capability, 'acme'), 'locked generator writes no mapping');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

console.log('\n5. marks generated files and safely removes only marked stale artifacts');
{
  const root = makeFixture([{ id: 'acme', pin: 'model:model-alpha', label: 'Acme' }]);
  try {
    const generatedPath = path.join(root, 'agents', 'acme.md');
    const rolePath = path.join(root, 'agents', 'planner.md');
    const roleBefore = fs.readFileSync(rolePath, 'utf8');

    let result = run(root);
    assertEq(result.status, 0, `initial generation succeeds: ${result.stderr}`);
    const generated = fs.readFileSync(generatedPath, 'utf8');
    assert(generated.includes(GENERATED_MARKER), 'generated agent carries an ownership marker');
    assertEq(readMap(root)[OWNERSHIP_KEY][0], 'acme', 'main map persists generated ownership');
    assertEq(readMap(root, true)[OWNERSHIP_KEY][0], 'acme', 'plugin map persists generated ownership');

    // Existing byte-identical pre-marker output can migrate once without weakening
    // collision protection for arbitrary role files.
    fs.writeFileSync(generatedPath, generated.replace(`${GENERATED_MARKER}\n\n`, ''));
    result = run(root);
    assertEq(result.status, 0, `legacy generated output migrates: ${result.stderr}`);
    assert(fs.readFileSync(generatedPath, 'utf8').includes(GENERATED_MARKER), 'migration restores marker');

    writeJson(path.join(root, 'config', 'brand-agents.json'), { agents: [] });
    result = run(root, '--check');
    assertEq(result.status, 1, 'check rejects stale generated artifacts after catalog removal');
    assert(result.stderr.includes('stale generated agents/acme.md'), 'check reports stale generated agent file');
    assert(result.stderr.includes("stale agent_to_capability['acme']"), 'check reports stale main mapping');
    assert(result.stderr.includes("stale plugin agent_to_capability['acme']"), 'check reports stale plugin mapping');
    assert(!result.stderr.includes('planner.md'), 'check does not classify functional role as generated');

    result = run(root);
    assertEq(result.status, 0, `stale cleanup succeeds: ${result.stderr}`);
    assert(!fs.existsSync(generatedPath), 'normal generation deletes marked stale agent');
    assertEq(fs.readFileSync(rolePath, 'utf8'), roleBefore, 'normal generation preserves functional role file');
    assert(!Object.hasOwn(readMap(root).agent_to_capability, 'acme'), 'normal generation removes stale main mapping');
    assert(!Object.hasOwn(readMap(root, true).agent_to_capability, 'acme'), 'normal generation removes stale plugin mapping');
    assertEq(readMap(root).agent_to_capability.planner, 'planner-hard', 'normal generation preserves role mapping');

    result = run(root, '--check');
    assertEq(result.status, 0, `check passes after owned cleanup: ${result.stderr}`);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

console.log('\n6. persisted ownership detects a stale mapping after its generated file is absent');
{
  const root = makeFixture([{ id: 'acme', pin: 'model:model-alpha', label: 'Acme' }]);
  try {
    let result = run(root);
    assertEq(result.status, 0, `initial generation succeeds: ${result.stderr}`);
    fs.unlinkSync(path.join(root, 'agents', 'acme.md'));
    writeJson(path.join(root, 'config', 'brand-agents.json'), { agents: [] });

    result = run(root, '--check');
    assertEq(result.status, 1, 'check rejects mapping-only stale ownership');
    assert(result.stderr.includes(`${OWNERSHIP_KEY}`), 'check reports stale ownership metadata');
    assert(result.stderr.includes("stale agent_to_capability['acme']"), 'check reports stale main mapping without agent file');
    assert(result.stderr.includes("stale plugin agent_to_capability['acme']"), 'check reports stale plugin mapping without agent file');

    result = run(root);
    assertEq(result.status, 0, `mapping-only cleanup succeeds: ${result.stderr}`);
    assert(!Object.hasOwn(readMap(root).agent_to_capability, 'acme'), 'cleanup removes mapping-only stale main pin');
    assert(!Object.hasOwn(readMap(root, true).agent_to_capability, 'acme'), 'cleanup removes mapping-only stale plugin pin');
    assertEq(readMap(root)[OWNERSHIP_KEY].length, 0, 'cleanup persists empty main ownership set');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

console.log('\n7. repurposed same-name role keeps its file and mapping');
{
  const root = makeFixture([{ id: 'acme', pin: 'model:model-alpha', label: 'Acme' }]);
  try {
    let result = run(root);
    assertEq(result.status, 0, `initial generation succeeds: ${result.stderr}`);
    const rolePath = path.join(root, 'agents', 'acme.md');
    const roleContent = '# Repurposed functional role\n';
    fs.writeFileSync(rolePath, roleContent);
    writeJson(path.join(root, 'config', 'brand-agents.json'), { agents: [] });
    for (const plugin of [false, true]) {
      const map = readMap(root, plugin);
      map.agent_to_capability.acme = 'planner-hard';
      const mapPath = plugin
        ? path.join(root, 'plugins', 'c-thru', 'config', 'model-map.json')
        : path.join(root, 'config', 'model-map.json');
      writeJson(mapPath, map);
    }

    result = run(root);
    assertEq(result.status, 0, `repurposed role cleanup succeeds: ${result.stderr}`);
    assertEq(fs.readFileSync(rolePath, 'utf8'), roleContent, 'repurposed role file is preserved');
    assertEq(readMap(root).agent_to_capability.acme, 'planner-hard', 'repurposed role mapping is preserved');
    assertEq(readMap(root, true).agent_to_capability.acme, 'planner-hard', 'repurposed plugin mapping is preserved');
    assertEq(readMap(root)[OWNERSHIP_KEY].length, 0, 'generated ownership is relinquished');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

console.log('\n8. a map edit during staging aborts without partially generating agents');
{
  const root = makeFixture([{ id: 'acme', pin: 'model:model-alpha', label: 'Acme' }]);
  try {
    const mapPath = path.join(root, 'config', 'model-map.json');
    const pluginPath = path.join(root, 'plugins', 'c-thru', 'config', 'model-map.json');
    const pluginBefore = fs.readFileSync(pluginPath, 'utf8');
    const rolePath = path.join(root, 'agents', 'planner.md');
    const roleBefore = fs.readFileSync(rolePath, 'utf8');
    const preloadPath = path.join(root, 'race-preload.js');
    fs.writeFileSync(preloadPath, [
      "'use strict';",
      "const fs = require('fs');",
      'const originalWrite = fs.writeFileSync;',
      'let injected = false;',
      'fs.writeFileSync = function patchedWrite(dest, ...args) {',
      '  const result = originalWrite.call(fs, dest, ...args);',
      "  if (!injected && typeof dest === 'string' && dest.endsWith('.stage') && dest.includes('.gen-brand-agents.')) {",
      '    injected = true;',
      '    const map = JSON.parse(fs.readFileSync(process.env.CTHRU_RACE_MAP, \"utf8\"));',
      "    map.concurrent_edit = 'keep-me';",
      "    originalWrite.call(fs, process.env.CTHRU_RACE_MAP, JSON.stringify(map, null, 2) + '\\n');",
      '  }',
      '  return result;',
      '};',
      '',
    ].join('\n'));

    const result = runWithEnv(root, {
      NODE_OPTIONS: `--require=${preloadPath}`,
      CTHRU_RACE_MAP: mapPath,
    });
    assertEq(result.status, 1, 'late concurrent map edit exits nonzero');
    assert(
      result.stderr.includes('config/model-map.json changed during generation'),
      'late concurrent map edit is identified',
    );
    assert(!fs.existsSync(path.join(root, 'agents', 'acme.md')), 'race leaves no generated agent file');
    assertEq(readMap(root).concurrent_edit, 'keep-me', 'race preserves the concurrent map edit');
    assert(!Object.hasOwn(readMap(root).agent_to_capability, 'acme'), 'race leaves main brand mapping untouched');
    assertEq(fs.readFileSync(pluginPath, 'utf8'), pluginBefore, 'race leaves plugin map untouched');
    assertEq(fs.readFileSync(rolePath, 'utf8'), roleBefore, 'race leaves functional roles untouched');
    assertEq(transactionTemps(root).length, 0, 'race cleans all staged transaction files');
    assert(!fs.existsSync(path.join(root, '.gen-brand-agents.lock')), 'race releases the generator lock');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

console.log('\n9. a plugin-map commit failure rolls back agents and the canonical map');
{
  const root = makeFixture([{ id: 'acme', pin: 'model:model-alpha', label: 'Acme' }]);
  try {
    const mapPath = path.join(root, 'config', 'model-map.json');
    const pluginPath = path.join(root, 'plugins', 'c-thru', 'config', 'model-map.json');
    const mapBefore = fs.readFileSync(mapPath, 'utf8');
    const pluginBefore = fs.readFileSync(pluginPath, 'utf8');
    const preloadPath = path.join(root, 'commit-failure-preload.js');
    fs.writeFileSync(preloadPath, [
      "'use strict';",
      "const fs = require('fs');",
      'const originalRename = fs.renameSync;',
      'let injected = false;',
      'fs.renameSync = function patchedRename(source, dest) {',
      "  if (!injected && typeof dest === 'string' && dest.includes('/plugins/c-thru/config/model-map.json') && typeof source === 'string' && source.endsWith('.stage')) {",
      '    injected = true;',
      "    const error = new Error('injected plugin-map commit failure');",
      "    error.code = 'EIO';",
      '    throw error;',
      '  }',
      '  return originalRename.call(fs, source, dest);',
      '};',
      '',
    ].join('\n'));

    const result = runWithEnv(root, {
      NODE_OPTIONS: `--require=${preloadPath}`,
    });
    assertEq(result.status, 1, 'plugin-map commit failure exits nonzero');
    assert(result.stderr.includes('transaction commit failed and was rolled back'), 'commit failure reports rollback');
    assert(!fs.existsSync(path.join(root, 'agents', 'acme.md')), 'rollback removes the partially committed agent');
    assertEq(fs.readFileSync(mapPath, 'utf8'), mapBefore, 'rollback restores the canonical map byte-for-byte');
    assertEq(fs.readFileSync(pluginPath, 'utf8'), pluginBefore, 'rollback leaves the plugin map byte-for-byte intact');
    assertEq(transactionTemps(root).length, 0, 'rollback cleans all staged transaction files');
    assert(!fs.existsSync(path.join(root, '.gen-brand-agents.lock')), 'rollback releases the generator lock');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

const failed = summary();
process.exit(failed ? 1 : 0);
