#!/usr/bin/env node
'use strict';
// Lineage snapshot test: asserts that every capability resolves to the exact
// expected concrete model for every mode × tier cell.
//
// Run:          node test/model-map-lineage.test.js
// Update snap:  node test/model-map-lineage.test.js --update
//
// What it tests
// ─────────────
// For each of the 20 pipeline + utility capabilities, call the same
// resolveCapabilityAlias → resolveProfileModel chain that claude-proxy
// runs on every live request. If a model-map.json edit silently changes a
// resolution, this test fails and forces an explicit --update acknowledgment.
//
// Cells that resolve to null (capability/mode/tier not configured) are
// recorded as null in the snapshot. A cell becoming non-null (or changing
// value) is equally a diff failure.

const fs   = require('fs');
const path = require('path');

const { resolveProfileModel, resolveCapabilityAlias, LLM_MODE_ENUM } = require('../tools/model-map-resolve.js');

const REPO_ROOT   = path.join(__dirname, '..');
const CONFIG_PATH = path.join(REPO_ROOT, 'config', 'model-map.json');

const TIERS = ['16gb', '32gb', '48gb', '64gb', '128gb'];
const MODES = [...LLM_MODE_ENUM];

// ── Expected snapshot ────────────────────────────────────────────────────────
// Generated by: node test/model-map-lineage.test.js --update
// Last updated: 2026-05-02
// Columns: mode → { tier → model }
// ─────────────────────────────────────────────────────────────────────────────
const SNAPSHOT = {
  "planner": {
    "best-cloud": { "16gb": "claude-opus-4-7", "32gb": "claude-opus-4-7", "48gb": "claude-opus-4-7", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-oss": { "16gb": "deepseek-v4-pro:cloud", "32gb": "deepseek-v4-pro:cloud", "48gb": "deepseek-v4-pro:cloud", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-local-oss": { "16gb": "phi4-reasoning:plus", "32gb": "qwen3:14b", "48gb": "qwen3:30b", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-gov": { "16gb": "claude-opus-4-7", "32gb": "claude-opus-4-7", "48gb": "claude-opus-4-7", "64gb": "claude-opus-4-7", "128gb": "gpt-oss-120b:TODO" },
    "best-local-gov": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "gpt-oss-20b:TODO", "64gb": "gpt-oss-120b:TODO", "128gb": "gpt-oss-120b:TODO" },
  },
  "planner-hard": {
    "best-cloud": { "16gb": "claude-opus-4-7", "32gb": "claude-opus-4-7", "48gb": "claude-opus-4-7", "64gb": "claude-opus-4-7", "128gb": "claude-opus-4-7" },
    "best-cloud-oss": { "16gb": "moonshotai/kimi-k2", "32gb": "moonshotai/kimi-k2", "48gb": "moonshotai/kimi-k2", "64gb": "moonshotai/kimi-k2", "128gb": "moonshotai/kimi-k2" },
    "best-local-oss": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "qwen3:14b", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-gov": { "16gb": "claude-opus-4-7", "32gb": "claude-opus-4-7", "48gb": "claude-opus-4-7", "64gb": "claude-opus-4-7", "128gb": "claude-opus-4-7" },
    "best-local-gov": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "gpt-oss-120b:TODO", "128gb": "gpt-oss-120b:TODO" },
  },
  "explore": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "qwen3:7b", "48gb": "qwen3:14b", "64gb": "qwen3:14b", "128gb": "qwen3:14b" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "qwen3:7b", "48gb": "qwen3:14b", "64gb": "qwen3:14b", "128gb": "qwen3:14b" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "qwen3:7b", "48gb": "qwen3:14b", "64gb": "qwen3:14b", "128gb": "qwen3:14b" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
  },
  "coder": {
    "best-cloud": { "16gb": "claude-sonnet-4-6", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "devstral-small-2:24b", "128gb": "devstral-small-2:24b" },
    "best-cloud-oss": { "16gb": "deepseek-v4-pro:cloud", "32gb": "deepseek-v4-pro:cloud", "48gb": "deepseek-v4-pro:cloud", "64gb": "devstral-small-2:24b", "128gb": "devstral-small-2:24b" },
    "best-local-oss": { "16gb": "phi4-reasoning:plus", "32gb": "devstral-small-2:24b", "48gb": "devstral-small-2:24b", "64gb": "devstral-small-2:24b", "128gb": "qwen3:30b" },
    "best-cloud-gov": { "16gb": "claude-sonnet-4-6", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "gpt-oss-20b:TODO" },
    "best-local-gov": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "gpt-oss-20b:TODO", "64gb": "gpt-oss-20b:TODO", "128gb": "gpt-oss-20b:TODO" },
  },
  "coder-fallback": {
    "best-cloud": { "16gb": "claude-haiku-4-5-20251001", "32gb": "claude-haiku-4-5-20251001", "48gb": "claude-sonnet-4-6", "64gb": "llama4:scout", "128gb": "llama4:scout" },
    "best-cloud-oss": { "16gb": "thudm/glm-4-plus", "32gb": "thudm/glm-4-plus", "48gb": "thudm/glm-4-plus", "64gb": "thudm/glm-4-plus", "128gb": "thudm/glm-4-plus" },
    "best-local-oss": { "16gb": "gemma4:e4b", "32gb": "gemma4:e4b", "48gb": "llama4:scout", "64gb": "llama4:scout", "128gb": "llama4:scout" },
    "best-cloud-gov": { "16gb": "claude-haiku-4-5-20251001", "32gb": "claude-haiku-4-5-20251001", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "gpt-oss-20b:TODO" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "gpt-oss-20b:TODO", "128gb": "gpt-oss-20b:TODO" },
  },
  "tester": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "qwen3:7b", "48gb": "qwen3:14b", "64gb": "qwen3:14b", "128gb": "qwen3:14b" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "qwen3:7b", "48gb": "qwen3:14b", "64gb": "qwen3:14b", "128gb": "qwen3:14b" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "qwen3:7b", "48gb": "qwen3:14b", "64gb": "qwen3:14b", "128gb": "qwen3:14b" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
  },
  "docs": {
    "best-cloud": { "16gb": "gemma4:e4b", "32gb": "gemma4:e4b", "48gb": "gemma4:e4b", "64gb": "gemma4:e4b", "128gb": "gemma4:e4b" },
    "best-cloud-oss": { "16gb": "gemma4:e4b", "32gb": "gemma4:e4b", "48gb": "gemma4:e4b", "64gb": "gemma4:e4b", "128gb": "gemma4:e4b" },
    "best-local-oss": { "16gb": "gemma4:e4b", "32gb": "gemma4:e4b", "48gb": "gemma4:e4b", "64gb": "gemma4:e4b", "128gb": "gemma4:e4b" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
  },
  "reviewer-routine": {
    "best-cloud": { "16gb": "claude-sonnet-4-6", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-oss": { "16gb": "deepseek-v4-pro:cloud", "32gb": "deepseek-v4-pro:cloud", "48gb": "deepseek-v4-pro:cloud", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-local-oss": { "16gb": "phi4-reasoning:plus", "32gb": "qwen3:14b", "48gb": "qwen3:30b", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-gov": { "16gb": "claude-sonnet-4-6", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "gpt-oss-20b:TODO" },
    "best-local-gov": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "gpt-oss-20b:TODO", "128gb": "gpt-oss-20b:TODO" },
  },
  "reviewer-security": {
    "best-cloud": { "16gb": "claude-opus-4-7", "32gb": "claude-opus-4-7", "48gb": "claude-opus-4-7", "64gb": "claude-opus-4-7", "128gb": "claude-opus-4-7" },
    "best-cloud-oss": { "16gb": "moonshotai/kimi-k2", "32gb": "moonshotai/kimi-k2", "48gb": "moonshotai/kimi-k2", "64gb": "moonshotai/kimi-k2", "128gb": "moonshotai/kimi-k2" },
    "best-local-oss": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "qwen3:14b", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-gov": { "16gb": "claude-opus-4-7", "32gb": "claude-opus-4-7", "48gb": "claude-opus-4-7", "64gb": "claude-opus-4-7", "128gb": "claude-opus-4-7" },
    "best-local-gov": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "gpt-oss-120b:TODO", "128gb": "gpt-oss-120b:TODO" },
  },
  "debugger-hypothesis": {
    "best-cloud": { "16gb": "claude-sonnet-4-6", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-oss": { "16gb": "deepseek-v4-pro:cloud", "32gb": "deepseek-v4-pro:cloud", "48gb": "deepseek-v4-pro:cloud", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-local-oss": { "16gb": "phi4-reasoning:plus", "32gb": "qwen3:14b", "48gb": "qwen3:30b", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-gov": { "16gb": "claude-sonnet-4-6", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "gpt-oss-20b:TODO" },
    "best-local-gov": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "gpt-oss-20b:TODO", "128gb": "gpt-oss-20b:TODO" },
  },
  "debugger-investigate": {
    "best-cloud": { "16gb": "claude-sonnet-4-6", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "devstral-small-2:24b", "128gb": "devstral-small-2:24b" },
    "best-cloud-oss": { "16gb": "deepseek-v4-pro:cloud", "32gb": "deepseek-v4-pro:cloud", "48gb": "deepseek-v4-pro:cloud", "64gb": "devstral-small-2:24b", "128gb": "devstral-small-2:24b" },
    "best-local-oss": { "16gb": "phi4-reasoning:plus", "32gb": "devstral-small-2:24b", "48gb": "devstral-small-2:24b", "64gb": "devstral-small-2:24b", "128gb": "qwen3:30b" },
    "best-cloud-gov": { "16gb": "claude-sonnet-4-6", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "gpt-oss-20b:TODO" },
    "best-local-gov": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "gpt-oss-20b:TODO", "64gb": "gpt-oss-20b:TODO", "128gb": "gpt-oss-20b:TODO" },
  },
  "debugger-hard": {
    "best-cloud": { "16gb": "claude-opus-4-7", "32gb": "claude-opus-4-7", "48gb": "claude-opus-4-7", "64gb": "claude-opus-4-7", "128gb": "claude-opus-4-7" },
    "best-cloud-oss": { "16gb": "moonshotai/kimi-k2", "32gb": "moonshotai/kimi-k2", "48gb": "moonshotai/kimi-k2", "64gb": "moonshotai/kimi-k2", "128gb": "moonshotai/kimi-k2" },
    "best-local-oss": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "qwen3:14b", "64gb": "qwen3:30b", "128gb": "qwen3:30b" },
    "best-cloud-gov": { "16gb": "claude-opus-4-7", "32gb": "claude-opus-4-7", "48gb": "claude-opus-4-7", "64gb": "claude-opus-4-7", "128gb": "claude-opus-4-7" },
    "best-local-gov": { "16gb": "phi4-reasoning:plus", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "gpt-oss-120b:TODO", "128gb": "gpt-oss-120b:TODO" },
  },
  "vision": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "qwen3.6:35b-a3b-coding-nvfp4", "48gb": "qwen3.6:35b-a3b-coding-nvfp4", "64gb": "qwen3.6:35b-a3b-coding-nvfp4", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "claude-sonnet-4-6" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "phi4-reasoning:plus", "128gb": "gpt-oss-20b:TODO" },
  },
  "pdf": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "qwen3.6:35b-a3b-coding-nvfp4", "48gb": "qwen3.6:35b-a3b-coding-nvfp4", "64gb": "qwen3.6:35b-a3b-coding-nvfp4", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "claude-sonnet-4-6" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "phi4-reasoning:plus", "128gb": "gpt-oss-20b:TODO" },
  },
  "writer": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "claude-opus-4-7" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "deepseek-v4-pro:cloud", "48gb": "deepseek-v4-pro:cloud", "64gb": "deepseek-v4-pro:cloud", "128gb": "moonshotai/kimi-k2" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "mistral-small3.1:24b", "48gb": "mistral-small3.1:24b", "64gb": "mistral-small3.1:24b", "128gb": "mistral-small3.1:24b" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "claude-opus-4-7" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "phi4-reasoning:plus", "128gb": "gpt-oss-20b:TODO" },
  },
  "edge": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "qwen3.6:27b-coding-nvfp4", "48gb": "qwen3.6:27b-coding-nvfp4", "64gb": "qwen3.6:27b-coding-nvfp4", "128gb": "qwen3-coder:30b" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "qwen3.6:27b-coding-nvfp4", "48gb": "qwen3.6:27b-coding-nvfp4", "64gb": "qwen3.6:27b-coding-nvfp4", "128gb": "qwen3-coder:30b" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "qwen3.6:27b-coding-nvfp4", "48gb": "qwen3.6:27b-coding-nvfp4", "64gb": "qwen3.6:27b-coding-nvfp4", "128gb": "qwen3-coder:30b" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
  },
  "generalist": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "deepseek-v4-pro:cloud", "48gb": "deepseek-v4-pro:cloud", "64gb": "deepseek-v4-pro:cloud", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "qwen3.6:35b-a3b-coding-nvfp4", "48gb": "qwen3.6:35b-a3b-coding-nvfp4", "64gb": "qwen3.6:35b-a3b-coding-nvfp4", "128gb": "qwen3.6:35b-a3b-coding-nvfp4" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "claude-sonnet-4-6" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "phi4-reasoning:plus", "128gb": "gpt-oss-20b:TODO" },
  },
  "fast-generalist": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "gemma4:26b", "48gb": "gemma4:26b", "64gb": "gemma4:26b", "128gb": "gemma4:26b" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "gemma4:26b", "48gb": "gemma4:26b", "64gb": "gemma4:26b", "128gb": "gemma4:26b" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "gemma4:26b", "48gb": "gemma4:26b", "64gb": "gemma4:26b", "128gb": "gemma4:26b" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
  },
  "fast-scout": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "gemma4:e2b", "48gb": "gemma4:e2b", "64gb": "gemma4:e2b", "128gb": "qwen3.6:27b-coding-nvfp4" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "gemma4:e2b", "48gb": "gemma4:e2b", "64gb": "gemma4:e2b", "128gb": "qwen3.6:27b-coding-nvfp4" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "gemma4:e2b", "48gb": "gemma4:e2b", "64gb": "gemma4:e2b", "128gb": "qwen3.6:27b-coding-nvfp4" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-mini", "48gb": "phi4-mini", "64gb": "phi4-mini", "128gb": "phi4-mini" },
  },
  "long-context": {
    "best-cloud": { "16gb": "qwen3:7b", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "claude-sonnet-4-6" },
    "best-cloud-oss": { "16gb": "qwen3:7b", "32gb": "deepseek-v4-pro:cloud", "48gb": "deepseek-v4-pro:cloud", "64gb": "deepseek-v4-pro:cloud", "128gb": "deepseek-v4-pro:cloud" },
    "best-local-oss": { "16gb": "qwen3:7b", "32gb": "qwen3.6:35b-a3b-coding-nvfp4", "48gb": "gpt-oss:20b", "64gb": "gpt-oss:20b", "128gb": "devstral-small-2:24b" },
    "best-cloud-gov": { "16gb": "phi4-mini", "32gb": "claude-sonnet-4-6", "48gb": "claude-sonnet-4-6", "64gb": "claude-sonnet-4-6", "128gb": "claude-sonnet-4-6" },
    "best-local-gov": { "16gb": "phi4-mini", "32gb": "phi4-reasoning:plus", "48gb": "phi4-reasoning:plus", "64gb": "gpt-oss-20b:TODO", "128gb": "gpt-oss-20b:TODO" },
  },
};

// ── Helpers ──────────────────────────────────────────────────────────────────
function buildActual(cfg) {
  const actual = {};
  for (const cap of Object.keys(SNAPSHOT)) {
    actual[cap] = {};
    const entry = (cfg.llm_profiles || {})[cap] || null;
    for (const mode of MODES) {
      actual[cap][mode] = {};
      for (const tier of TIERS) {
        actual[cap][mode][tier] = entry ? (resolveProfileModel(entry, tier, mode) || null) : null;
      }
    }
  }
  return actual;
}

function diff(expected, actual) {
  const diffs = [];
  for (const cap of Object.keys(expected)) {
    for (const mode of MODES) {
      for (const tier of TIERS) {
        const exp = (expected[cap]?.[mode]?.[tier]) ?? null;
        const got = (actual[cap]?.[mode]?.[tier]) ?? null;
        if (exp !== got) {
          diffs.push({ cap, mode, tier, expected: exp, got });
        }
      }
    }
  }
  return diffs;
}

function snapshotSource(actual) {
  const lines = ['const SNAPSHOT = {'];
  for (const cap of Object.keys(actual)) {
    lines.push(`  ${JSON.stringify(cap)}: {`);
    for (const mode of MODES) {
      const cells = TIERS.map(t => {
        const v = actual[cap][mode][t];
        return `${JSON.stringify(t)}: ${JSON.stringify(v)}`;
      }).join(', ');
      lines.push(`    ${JSON.stringify(mode)}: { ${cells} },`);
    }
    lines.push('  },');
  }
  lines.push('};');
  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────────────────────────
const UPDATE = process.argv.includes('--update');

const cfg = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
const actual = buildActual(cfg);

if (UPDATE) {
  const self = fs.readFileSync(__filename, 'utf8');
  const newSnap = snapshotSource(actual);
  const updated = self.replace(
    /\/\/ ── Expected snapshot ──[\s\S]*?\n\};\n\/\/ ─{5,}\n/,
    `// ── Expected snapshot ────────────────────────────────────────────────────────\n// Generated by: node test/model-map-lineage.test.js --update\n// Last updated: ${new Date().toISOString().slice(0,10)}\n// Columns: mode → { tier → model }\n// ─────────────────────────────────────────────────────────────────────────────\n${newSnap}\n// ─────────────────────────────────────────────────────────────────────────────\n`
  );
  fs.writeFileSync(__filename, updated);
  console.log('Snapshot updated.');
  process.exit(0);
}

// ── Assertions ───────────────────────────────────────────────────────────────
let passed = 0;
let failed = 0;

// 1. Snapshot coverage: every capability in SNAPSHOT must exist in llm_profiles
console.log('\n1. Capability presence in llm_profiles');
for (const cap of Object.keys(SNAPSHOT)) {
  const present = !!(cfg.llm_profiles || {})[cap];
  if (present) {
    console.log(`  PASS  ${cap}: present in llm_profiles`);
    passed++;
  } else {
    console.error(`  FAIL  ${cap}: missing from llm_profiles`);
    failed++;
  }
}

// 2. agent_to_capability identity mapping for all pipeline agents
console.log('\n2. agent_to_capability identity map');
const PIPELINE_CAPS = [
  'planner', 'planner-hard', 'explore', 'coder', 'coder-fallback',
  'tester', 'docs', 'reviewer-routine', 'reviewer-security',
  'debugger-hypothesis', 'debugger-investigate', 'debugger-hard',
];
const a2c = cfg.agent_to_capability || {};
for (const cap of PIPELINE_CAPS) {
  if (a2c[cap] === cap) {
    console.log(`  PASS  agent_to_capability['${cap}'] === '${cap}' (identity)`);
    passed++;
  } else {
    console.error(`  FAIL  agent_to_capability['${cap}'] === '${a2c[cap]}' (expected '${cap}')`);
    failed++;
  }
}

// 3. Full resolution matrix snapshot
console.log('\n3. Resolution matrix (capability × mode × tier)');
const diffs = diff(SNAPSHOT, actual);
const totalCells = Object.keys(SNAPSHOT).length * MODES.length * TIERS.length;
if (diffs.length === 0) {
  console.log(`  PASS  all ${totalCells} cells match snapshot`);
  passed++;
} else {
  console.error(`  FAIL  ${diffs.length} cell(s) differ from snapshot:`);
  for (const d of diffs) {
    console.error(`        ${d.cap} / ${d.mode} / ${d.tier}: expected ${JSON.stringify(d.expected)} got ${JSON.stringify(d.got)}`);
  }
  console.error(`\n  Run with --update to accept new values.`);
  failed++;
}

// 4. No capability resolves to null at best-cloud for any tier
// (best-cloud is the unconditional fallback; a null here means the cell is
// completely unconfigured, which would cause a 503 in production.)
console.log('\n4. best-cloud must resolve for every capability at every tier');
for (const cap of Object.keys(actual)) {
  for (const tier of TIERS) {
    const v = actual[cap]['best-cloud'][tier];
    if (v !== null) {
      console.log(`  PASS  ${cap} / best-cloud / ${tier} → ${v}`);
      passed++;
    } else {
      console.error(`  FAIL  ${cap} / best-cloud / ${tier}: null (unconfigured — will 503 in production)`);
      failed++;
    }
  }
}

// 5. USGov modes must not resolve to Chinese-origin models
console.log('\n5. USGov modes: no Chinese-origin models');
const { isChineseOrigin } = require('../tools/model-map-resolve.js');
const GOV_MODES = ['best-cloud-gov', 'best-local-gov'];
for (const cap of Object.keys(actual)) {
  for (const mode of GOV_MODES) {
    for (const tier of TIERS) {
      const v = actual[cap][mode][tier];
      if (!v) continue;
      if (!isChineseOrigin(v)) {
        console.log(`  PASS  ${cap} / ${mode} / ${tier} → ${v} (non-Chinese)`);
        passed++;
      } else {
        console.error(`  FAIL  ${cap} / ${mode} / ${tier} → ${v} is Chinese-origin (gov-mode violation)`);
        failed++;
      }
    }
  }
}

// ── Summary ──────────────────────────────────────────────────────────────────
console.log(`\n${passed + failed} tests: ${passed} passed, ${failed} failed`);
if (failed > 0) process.exit(1);
